version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: travelnest-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - travelnest-net
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'mysqladmin ping -h localhost -u ${DB_USER} -p${DB_PASSWORD}',
        ]
      interval: 30s
      timeout: 10s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: travelnest-redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    command: ['redis-server', '--appendonly', 'yes']
    networks:
      - travelnest-net
    healthcheck:
      test: ['CMD-SHELL', 'redis-cli ping']
      interval: 30s
      timeout: 10s
      retries: 5

  minio:
    image: minio/minio:latest
    container_name: minio
    command: server /data --console-address ":9001"
    ports:
      - '9000:9000' # API
      - '9001:9001' # Web console
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    volumes:
      - ../minio-data:/data
    networks:
      - travelnest-net

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    container_name: travelnest-zookeeper
    restart: unless-stopped
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - '2181:2181'
    networks:
      - travelnest-net

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: travelnest-kafka
    restart: unless-stopped
    depends_on:
      - zookeeper
    ports:
      - '9092:9092'
      - '29092:29092'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - travelnest-net
    healthcheck:
      test:
        ['CMD-SHELL', 'kafka-topics --bootstrap-server localhost:9092 --list']
      interval: 10s
      timeout: 5s
      retries: 5

  # kafka-consumer:
  #   build:
  #     context: ..
  #     dockerfile: infra/Dockerfile.dev
  #     args:
  #       ENV_FILE: .env.development
  #   container_name: travelnest-kafka-consumer
  #   restart: unless-stopped
  #   depends_on:
  #     kafka:
  #       condition: service_healthy
  #   command: ['node', 'kafka/worker.js']
  #   environment:
  #     NODE_ENV: development
  #     KAFKA_CLIENT_ID: my-kafka
  #     KAFKA_BROKERS: kafka:9092
  #   networks:
  #     - travelnest-net

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: travelnest-kafka-ui
    restart: unless-stopped
    depends_on:
      - kafka
    ports:
      - '8080:8080'
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    networks:
      - travelnest-net

networks:
  travelnest-net:
    driver: bridge

volumes:
  mysql_data:
  redis_data:
