version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: travelnest-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - travelnest-net
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'mysqladmin ping -h localhost -u ${DB_USER} -p${DB_PASSWORD}',
        ]
      interval: 30s
      timeout: 10s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: travelnest-redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    command: ['redis-server', '--appendonly', 'yes']
    networks:
      - travelnest-net
    healthcheck:
      test: ['CMD-SHELL', 'redis-cli ping']
      interval: 30s
      timeout: 10s
      retries: 5

  minio:
    image: minio/minio:latest
    container_name: minio
    command: server /data --console-address ":9001"
    ports:
      - '9000:9000' # API
      - '9001:9001' # Web console
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    volumes:
      - ./minor-data:/data
    networks:
      - travelnest-net

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: travelnest-rabbitmq
    restart: unless-stopped
    ports:
      - '5672:5672' # AMQP port
      - '15672:15672' # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-guest}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS:-guest}
      RABBITMQ_DEFAULT_VHOST: /
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - travelnest-net
    healthcheck:
      test: ['CMD-SHELL', 'rabbitmq-diagnostics -q ping']
      interval: 30s
      timeout: 10s
      retries: 5

  # rabbitmq-consumer:
  #   build:
  #     context: ..
  #     dockerfile: infra/Dockerfile.dev
  #     args:
  #       ENV_FILE: .env.development
  #   container_name: travelnest-rabbitmq-consumer
  #   restart: unless-stopped
  #   depends_on:
  #     rabbitmq:
  #       condition: service_healthy
  #   command: ['node', 'rabbitmq/worker.js']
  #   environment:
  #     NODE_ENV: development
  #     RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
  #   networks:
  #     - travelnest-net

networks:
  travelnest-net:
    driver: bridge

volumes:
  mysql_data:
  redis_data:
  rabbitmq_data:
